name: Ruby Current Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
      - '*-stable'
      - '*-dev'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: "3.3"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
          - ruby: "3.3"
            appraisal: "rails-7-0"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
          - ruby: "3.2"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
          - ruby: "3.2"
            appraisal: "rails-7-0"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
          #- '3.1' - 3.1 tests are run by coverage.yml
          - ruby: "truffleruby"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
          - ruby: "jruby"
            appraisal: "rails-7-1"
            rubygems: latest
            bundler: latest
            gemfile: vanilla
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{matrix.ruby}}-${{matrix.appraisal}}-${{ hashFiles('gemfiles/*.gemfile.lock') }}
      - name: Setup Ruby & Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: false
      - name: Bundle for Appraisal ${{ matrix.appraisal }}
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run tests ${{ matrix.appraisal }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec rake test
